version: "3"

volumes: 
  static_volume:
services:
  nginx:
    restart: always
    image: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - "./frontend/www:/usr/share/nginx/html"
      - "./backend/media:/media"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/nginx.dev.conf:/etc/nginx/conf.d/default.conf"
      - "./backend:/src"
    command: ["nginx","-g","daemon off;"]
  db:
    image: postgres:11.9
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432"
  frontend:
    build:
      context: frontend/
      args:
        VERSION: ${VERSION}
    volumes:
      - "./frontend/src:/usr/src/fupot/src"
      - "./frontend/www:/usr/src/fupot/www"
      - "./frontend/node_modules:/usr/src/fupot/node_modules"
  backend:
    restart: always
    build:
      context: backend/
    volumes:
      - "./backend:/src"
      - "./backend:/backend"
      - "./frontend/www:/static"
      - "./backend/media:/media"
    ports:
      - "8000:8000"
    depends_on:
      - db
