# Generated by Django 3.1.1 on 2020-12-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201214_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fucoins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='login_streak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='num_wins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.CharField(blank=True, default='human', max_length=63, null=True),
        ),
    ]
