# Generated by Django 3.0.7 on 2020-09-08 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('join_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='fupot/questions/backgrounds/')),
                ('closed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('has_winner', models.BooleanField(default=False)),
                ('max_winners', models.IntegerField(default=1)),
                ('num_submissions', models.IntegerField(default=0)),
                ('prompt', models.TextField(blank=True, max_length=1027, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField()),
                ('title', models.CharField(max_length=255, unique=True)),
                ('answers_1', models.CharField(help_text='Enter the answer text that                                             you want displayed', max_length=1000)),
                ('answers_2', models.CharField(help_text='Enter the answer text that                                             you want displayed', max_length=1000)),
                ('answers_3', models.CharField(help_text='Enter the answer text that                                             you want displayed', max_length=1000)),
                ('answers_4', models.CharField(help_text='Enter the answer text that                                             you want displayed', max_length=1000)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fupot.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Win',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fupot.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscribed_notifiaction', models.BooleanField(default=False)),
                ('correct', models.BooleanField(default=False, help_text='Is this a correct answer?', verbose_name='Correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fupot.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
