# Generated by Django 3.1.1 on 2021-04-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fupot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers_1',
            field=models.CharField(blank=True, help_text='Enter the answer text that                                             you want displayed', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers_2',
            field=models.CharField(blank=True, help_text='Enter the answer text that                                             you want displayed', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers_3',
            field=models.CharField(blank=True, help_text='Enter the answer text that                                             you want displayed', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers_4',
            field=models.CharField(blank=True, help_text='Enter the answer text that                                             you want displayed', max_length=1000, null=True),
        ),
    ]
