# Generated by Django 3.1.1 on 2021-01-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fupot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_img',
            field=models.ImageField(blank=True, null=True, upload_to='fupot/owner/img/'),
        ),
    ]
