# Generated by Django 3.1.1 on 2020-11-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fupot', '0002_gameroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='join_id',
        ),
        migrations.RemoveField(
            model_name='group',
            name='location',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='location',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
