# Generated by Django 3.1.1 on 2020-12-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fupot', '0003_remove_result_question_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='extra_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='loser_body',
            field=models.TextField(blank=True, max_length=1027, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='loser_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='winner_body',
            field=models.TextField(blank=True, max_length=1027, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='winner_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
