# Generated by Django 3.1.1 on 2020-12-25 04:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fupot', '0006_auto_20201224_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AddField(
            model_name='group',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
