# Generated by Django 3.1.1 on 2020-12-25 18:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fupot', '0007_auto_20201225_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='submission',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
