# Generated by Django 3.1.1 on 2020-12-26 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fupot', '0008_auto_20201225_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='location',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='longitude',
        ),
    ]
