# Generated by Django 3.1.1 on 2020-12-26 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fupot', '0009_auto_20201226_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fupot.question', unique=True),
        ),
    ]
