# Generated by Django 3.1.1 on 2020-12-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fupot', '0012_ownerstatistics_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerstatistics',
            name='group_members',
        ),
    ]
